name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0
      with:
        persist-credentials: false
        submodules: 'true'
    - name: Set up Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # tag=v5.4.0
      with:
        java-version: 21
        distribution: "temurin"
        cache: "maven"
    - name: Check formatting
      run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        java-version:
        - 21
        - 25
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0
      with:
        persist-credentials: false
        submodules: 'true'
    - name: Set up Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # tag=v5.4.0
      with:
        java-version: ${{ matrix.java-version }}
        distribution: "temurin"
        cache: "maven"
    - name: Test
      run: make test
