name: Integration Test

on:
  schedule:
  - cron: "0 4 * * *"
  workflow_dispatch: { }

permissions: { }

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0
      with:
        persist-credentials: false
        submodules: 'true'
    - name: Set up Java
      uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # tag=v5.5.0
      with:
        java-version: 21
        distribution: "temurin"
        cache: "maven"
    - name: Integration Test
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn -B test-compile failsafe:integration-test
    - name: Upload Integration Test Results
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # tag=v7.0.1
      with:
        name: test-results
        path: versatile-core/target/results/*.json
